### ISSUE TITLE
HA log errors ref 2025.1

### ISSUE THREAD

**Issue by timvdsm** [kesteraernoudt/dobiss#175]
## Version of the custom_component
Latest version

## Describe the bug
Hi,
I just saw some errors in the HA logbook referring to 2025.1. 
I guess it's just a remark for future incompatibility as from the 2025.1 CORE release, so nothing urgent :-)

## Erros in log: 
<img width="1275" alt="Scherm­afbeelding 2024-01-11 om 11 14 09" src="https://github.com/kesteraernoudt/dobiss/assets/14946020/a77400a4-b31b-40cb-b6de-e6d138eda38a">

<img width="1276" alt="Scherm­afbeelding 2024-01-11 om 11 16 07" src="https://github.com/kesteraernoudt/dobiss/assets/14946020/fb96000c-500d-4880-8565-e7912383023e">

<img width="1278" alt="Scherm­afbeelding 2024-01-11 om 11 16 43" src="https://github.com/kesteraernoudt/dobiss/assets/14946020/4723b5b0-d85d-49fe-934c-48294529cb56">

<img width="1280" alt="Scherm­afbeelding 2024-01-11 om 11 17 10" src="https://github.com/kesteraernoudt/dobiss/assets/14946020/8f6add88-626a-4308-89af-25554f9263bd">

Thanks!

**Comment by Eightball1990** [comment]
Hi kesteraernoudt,

i was wondering if you still intend to address the issue reported by timvdsm, i also noticed some additional warnings in my log about deprecated supported features values which will be removed in HA Core.

i'm not sure how timvdsm was able to present them this nicely, i uploaded the log file with the warnings:

[home-assistant_2024-12-26T19-39-24.371Z.log](https://github.com/user-attachments/files/18255149/home-assistant_2024-12-26T19-39-24.371Z.log)

I hope you find some time to address it sometime, i really appeciate your work!

Cheers!

**Comment by kesteraernoudt** [comment]
I'll see if I can find a solution for these. Problem is that I don't have a dobiss installation any more to test things out. I do welcome pull requests btw if you or someone else would have done some work on this!

**Comment by Eightball1990** [comment]
Hi, I have never written any Home Assistant code nor do I know python or contributed to any software / code development before (I do know some Javascrip, MATLAB, C++ and VBA, but only used it for engineering calculation purposes). 
Also other than downloading code from GitHub and making comments, i'm not sure how things work around here and should be done and documented. 
But I am willing to learn and try. 

My guess from the error logs is that I just need to dive into your code and try to rename/replace deprecated functions with the (name of the) new function, test and then make a pull request after which you integrate it in a new formal release, is this correct? 
Can you maybe tell me how to get started and explain how I can safely test code without messing up my home assistant installation?

Btw have you ever reached out to Dobiss Domotica or  Fermax to check if they are willing to continue your work and maybe make an official supported integration?

**Comment by rmeekers** [comment]
I've just upgraded to 2025.1 and as a result all of my entities are disabled. "No longer provided by the integration "

**Comment by rmeekers** [comment]
These are the logs telling me

```
Logger: homeassistant.components.light
Source: helpers/entity_platform.py:608
integration: Light (documentation, issues)
First occurred: 07:42:33 (102 occurrences)
Last logged: 09:12:43

Error adding entity None for domain light with platform dobiss
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 608, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 825, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 1116, in capability_attributes
    if LightEntityFeature.EFFECT in supported_features:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable

```

And this

```

Logger: homeassistant.components.light
Source: components/light/__init__.py:1323
integration: Light (documentation, issues)
First occurred: 07:42:33 (102 occurrences)
Last logged: 09:12:43

None (<class 'custom_components.dobiss.light.HADobissLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/kesteraernoudt/dobiss/issues

```

**Comment by migueldc73** [comment]
I have the same issue after upgrading to Core 2025.1

What still works : curtains and covers (garage, pool)
What stopped working : all lights (on/off and dimmable)

Can't test more as I am currently abroad, just received a panicky message from the home front "nothing worked anymore", so rolled back to 2024.12 for now.

**Comment by kesteraernoudt** [comment]
I've got the changes done locally, but haven't found a way to test this. I don't want to break all by pushing the changes online without a test first... 

The best way to help out would be to clone the repo on GitHub, and do the modifications there and test them. If they work for you, issue a pull request so I can merge them into my repo.

I did talk to Fermax indeed, they were interested in taking this on at some point, but I think they don't have the time to maintain this, so for now this has been pushed out. But I would recommend you all independently to contact them and ask the question - the more they hear it, the more chances we have of them supporting this...

Meanwhile, I'll try to push my changes after testing ...

**Comment by kesteraernoudt** [comment]
I did just push those changes to the dev branch. But with the current HA versions, I don't know how we can test these. If someone figures out a way to test it, and can give me the logs and feedback, that would be great

**Comment by Miolosh** [comment]
For me, my lights are working again and thanks to @timvdsm i can see the status again as well :)
Someone else will have to see if the color and dimmable is working. 

No notifications anymore on deprecated integrations

**Comment by samvanwelden** [comment]
> For me, my lights are working again and thanks to @timvdsm i can see the status again as well :) Someone else will have to see if the color and dimmable is working.
> 
> No notifications anymore on deprecated integrations

can you give a short tutorial how you got this working again? Is there a sequence to follow?

**Comment by kesteraernoudt** [comment]
I've created a new release, v1.10, which should work with the 2025 versions of HA

Thanks to all for contributing and helping - thanks @Miolosh for your pull requests!

**Comment by rmeekers** [comment]
Thank you @kesteraernoudt 🙏

**Comment by Eightball1990** [comment]
> I've got the changes done locally, but haven't found a way to test this. I don't want to break all by pushing the changes online without a test first...
> 
> The best way to help out would be to clone the repo on GitHub, and do the modifications there and test them. If they work for you, issue a pull request so I can merge them into my repo.
> 
> I did talk to Fermax indeed, they were interested in taking this on at some point, but I think they don't have the time to maintain this, so for now this has been pushed out. But I would recommend you all independently to contact them and ask the question - the more they hear it, the more chances we have of them supporting this...
> 
> Meanwhile, I'll try to push my changes after testing ...

Thank you @kesteraernoudt  for the update and thank you @Miolosh for testing it!

There is still one remaining warnings and one new warning popping up after this update, i'll open a new issue for these.

Nevertheless I will also reach out to Fermax with the request that they make an officialy supported add-in for HA startign from your great work. I'll also ask if they could support reading the button switch statuses and other status data that is currently not available via the API. I encourage anyone reading this to do the same and contact them at:

_FERMAX Belgium NV
Nieuwstraat 10
1570 Galmaarden
+32 (0)54 31 82 80 
info@dobiss.com_

cheers!
